### ISSUE TITLE
Utilities and Communications -> Utilities and Communication

### ISSUE THREAD

**Issue by karenmajewicz** [mjanowiecki/geoportal#1]
Hi Michelle!

I am updating documentation everywhere, because I have made a mistake on a bunch of documents. The ISO Topic Category is supposed to be "Utilities and Communication" and not with an 's' on the end.

**Comment by mjanowiecki** [comment]
oh thank you!

**Comment by mjanowiecki** [comment]
I think this is updated now :) #https://github.com/mjanowiecki/geoportal/commit/03789934b718af952472765fdab622ab39f0b067
